### ISSUE TITLE
Battle.net changing the way it handles API calls - all plugins need updating

### ISSUE THREAD

**Issue by RaefWolfe** [sawprogramming/WoW-Raid-Manager#53]
Blizzard is changing its back-end for developers.

No longer https://dev.battle.net/; now it's https://develop.battle.net/.

It's all oauth now.

There's a migration guide:  https://develop.battle.net/documentation/guides/migration-guide

...and the URLs will be changing. battle.net/wow becomes blizzard.com/data/wow, for example

This change will need to be done by January 6th, otherwise everything stops working.

**Comment by sawprogramming** [comment]
Yikes! I'll look into this soon. Thanks for keeping me informed!

**Comment by RaefWolfe** [comment]
We ended up making the following changes to get it working.

This is the new WowApi.php file

https://pastebin.com/dx16tDr0

I hard-coded my own region / client ID / secret just for the ease of it (replace USERCLIENTID and USERCLIENTSECRET), but that should help!

**Comment by sawprogramming** [comment]
Thanks for a solution; I'm glad it was nothing major! I'll try to look over it this weekend and apply the needed changes.

**Comment by Scabbrox** [comment]
I'm guessing this isn't being updated anytime soon?  New raids are out and would be nice to be able to get it working.

**Comment by Scabbrox** [comment]
> We ended up making the following changes to get it working.
> 
> This is the new WowApi.php file
> 
> https://pastebin.com/dx16tDr0
> 
> I hard-coded my own region / client ID / secret just for the ease of it (replace USERCLIENTID and USERCLIENTSECRET), but that should help!

Hi there.

As it's been two months since the last update and it doesn't look like any fix is being pushed anytime soon, is there any chance you could give me some more info on how to change your pastebin to get this working again for us too?

I have replaced the USERCLIENTID and USERCLIENTSECRET with the ones I have over at develop.battle.net and replaced the WowApi.php file but it still isn't working.  Is there anything else I need to change in the file?  We're an EU based guild rather than US.

I also had a client ID in the old WowApi file that doesn't seem to have anywhere to go here, do I still need to add that in before the new section on OATH you added?

Any help would be appreciated.

Thanks.

p.s. Hope all is well with the author and that the long silence is not due to anything untoward.

**Comment by sawprogramming** [comment]
Hey all, 

Sorry it's been quite some time! I recently got married and that ended up taking lots more time than I thought at the beginning of the year to finalize plans as it got closer!

I just looked over the changes RaefWolfe made and modified them to fit on my copy of the code in the style of the application. I have it working, so I'll be committing soon.

**Comment by sawprogramming** [comment]
If you're still using this, grab the update and let me know how it works!

**Comment by Scabbrox** [comment]
Will do.  Thanks and congratulations on your marriage!
